export const ICONS = {
  ARROW_DOWN: require('./arrowDown.png'),
  ARROW_DOWN_2: require('./arrowDown2.png'),
  ARROW_LEFT_DARK: require('./arrowLeftDark.png'),
  ARROW_LEFT_DARK_SVG: require('./arrowLeftDark.svg'),
  ARROW_LEFT_LIGHT_SVG: require('./arrowLeftLight.svg'),
  ARROW_RIGHT: require('./arrowRight.png'),
  ARROW_RIGHT_DARK: require('./arrowRightDark.png'),
  ARROW_TOP: require('./arrowTop.png'),
  BLACK_CROSS: require('./blackCross.png'),
  PAPER_AIRPLANE: require('./paperAirplane.png'),
  BURGER: require('./burger.png'),
  BURGER_CROSS: require('./burgerCross.png'),
  CROSS_LOGO: require('./crossLogo.svg'),
  FACEBOOK: require('./facebook.png'),
  FACEBOOK_ROUNDED: require('./facebookRounded.png'),
  FACEBOOK_WHITE: require('./facebookWhite.svg'),
  FILTER: require('./filter.png'),
  LINKEDIN: require('./linkedin.png'),
  LINKEDIN_WHITE: require('./linkedinWhite.svg'),
  SEARCH: require('./search.png'),
  TWITTER: require('./twitter.png'),
  WHITE_ARROW_DOWN: require('./whiteArrowDown.svg'),
};
